source 'https://rubygems.org'

gem 'rails', '4.1.8'

# database - postgres
gem 'pg'

# Assets
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'devise'

# Misc
gem 'sdoc', '~> 0.4.0',          group: :doc

# Auth
gem 'devise'

group :test, :development do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end

group :development do
  gem 'spring'
  gem 'pry'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem "rack-livereload"
  gem 'better_errors'
end

group :production do
  gem 'rails_12factor'
  gem 'unicorn'
end
